services:
  - type: web
    plan: free
    name: Filetolink
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: pythom -m Adarsh
    repo: https://github.com/Guardianff/Rederlinkbot.git
    branch: main
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: BIN_CHANNEL
        sync: false
      - key: OWNER_ID
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: ENV
        sync: false
      - key: PORT
        sync: false
      - key: NO_PORT
        sync: false
      - key: HAS_SSL
        sync: false
      - key: MY_PASS
        sync: false
      - key: SESSION_NAME
        sync: false
      - key: FQDN
        sync: false
    autoDeploy: true
